apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sentinelforge
  namespace: argocd
  labels:
    app.kubernetes.io/name: sentinelforge
    app.kubernetes.io/part-of: sentinelforge
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jay240322/sentinelforge.git
    targetRevision: develop
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: sentinelforge
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
